config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

    validates :name, uniqueness: true, presence: true
    validates :address, presence: true
    validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
      end
    
      def create
        @review = Review.new(review_params)
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review.restaurant = @restaurant
        if @review.save
          redirect_to restaurant_path(@restaurant)
        else
          render :new
        end
      end
    
      private
    
      def review_params
        params.require(:review).permit(:content, :rating)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <!-- ... -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
  <%= f.submit "Add Restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Category</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= link_to restaurant.name, restaurant %></td>
          <td><%= restaurant.address %></td>
          <td><%= restaurant.phone_number %></td>
          <td><%= restaurant.category %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to 'Add New Restaurant', new_restaurant_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container col-6-offset-3">
  <h1>New restaurant</h1>
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Address</th>
        <td><%= @restaurant.address %></td>
      </tr>
      <tr>
        <th scope="row">Phone Number</th>
        <td><%= @restaurant.phone_number %></td>
      </tr>
      <tr>
        <th scope="row">Category</th>
        <td><%= @restaurant.category %></td>
      </tr>
      <tr>
        <th scope="row">Rating</th>
        <% if @restaurant.reviews.present? %>
          <% @restaurant.reviews.each do |review| %>
          <td>⭐️ <strong><%= review.rating %></strong> - <%= review.content %></td>
          <% end %>
        <% else %>
          <td>This restaurant has no reviews yet. 🙁</td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <div>
    <%= link_to 'Go back', restaurants_path, class: 'btn btn-primary' %>
    <%= link_to 'Add a Review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary' %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container col-6-offset-3">

  <h1>New review for <%=  @restaurant.name %></h1>
  <div>
    <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit "Add the Review", class: "btn btn-primary" %>
    <% end %>
    <div>
      <%= link_to 'Cancel', restaurants_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>